version: '3'

volumes:
  data:
  
services:
  bighealth-metrics-service:
    image: bighealth-metrics:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - data:/var/lib/metrics-service